### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SimonNordon4** [SimonNordon4/blender-to-unity#10]
- [ ] Fix .Blend Default Importer py scripts by overwriting it.

- [ ] Use Asset Pre Processor on Blend Script to Override the Asset Importer.

- [ ] Use Custom Blend Importer to run python script from C# to process Blend Model and convert it to ublend.
